version: '3'

services:
  backend:
    build:
      context: ../
      dockerfile: devtools/go/Dockerfile
      volumes:
        type: bind
        source: "./backend"
        target: "/backend"
      environment:
        TZ=Asia/Tokyo