version: "3.9"

services:

  backend:
    build:
      context: ../
      dockerfile: devtools/go/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ../backend
        target: /usr/src/app/backend